name: Donetick Addon Test
version: "1.1.70"
slug: donetick
description: Simplify Tasks & Chores, Together.
url: "https://github.com/dawogid/hassio-addons/tree/main/donetick"
arch:
  - armv7
  - aarch64
  - amd64
init: false
map:
  - type: data
    read_only: false
    path: /data
environment:
  DT_SQLITE_PATH: /data/donetick.db
  DT_ENV: selfhosted
ports:
  80/tcp: 8005
  2021/tcp: 2021
webui: http://[HOST]:[PORT:2021]
image: "ghcr.io/dawogid/donetick-hassio-addons"

options:
  telegram_token: ""
  pushover_token: ""
  disable_signup: false
  is_user_creation_disabled: false
  auth_provider: ""
  oauth2_client_id: ""
  oauth2_client_secret: ""
  oauth2_redirect_uri: ""
  oauth2_auth_url: ""
  oauth2_token_url: ""
  oauth2_user_info_url: ""
  oauth2_name: ""
  jwt_secret: ""
  storage_type: "remote"
  storage_bucket: ""
  storage_region: ""
  storage_base_path: "assets"
  storage_access_key: ""
  storage_secret_key: ""
  storage_endpoint: ""
  storage_public_host: ""
  storage_max_user_storage: 0
  storage_max_file_size: 0

schema:
  telegram_token: "str?"
  pushover_token: "str?"
  disable_signup: "bool?"
  is_user_creation_disabled: "bool?"
  auth_provider: "str?"
  oauth2_client_id: "str?"
  oauth2_client_secret: "str?"
  oauth2_redirect_uri: "str?"
  oauth2_auth_url: "str?"
  oauth2_token_url: "str?"
  oauth2_user_info_url: "str?"
  oauth2_name: "str?"
  jwt_secret: "str?"
  storage_type: "str?"
  storage_bucket: "str?"
  storage_region: "str?"
  storage_base_path: "str?"
  storage_access_key: "str?"
  storage_secret_key: "str?"
  storage_endpoint: "str?"
  storage_public_host: "str?"
  storage_max_user_storage: "int?"
  storage_max_file_size: "int?"
