# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Donetick Addon
version: "1.0.13"
slug: Donetick
description: Simplify Tasks & Chores, Together.
url: "https://github.com/Donetick/hassio-addons/tree/main/donetick"
arch:
  - armv7
  - aarch64
  - amd64
init: false
map:
  - type: data
    read_only: False
    path: /data
environment:
  DT_SQLITE_PATH: /data/donetick.db
  DT_ENV: selfhosted
ports:
  80/tcp: 8005
  2021/tcp: 2021
webui: http://[HOST]:[PORT:2021]
image: "ghcr.io/donetick/{arch}-hassio-addons"
options:
  telegram_token: ""
schema:
  telegram_token: "str?"
